"""empty message

Revision ID: eab416c85d48
Revises: f961d3adb6cf
Create Date: 2023-02-25 14:36:58.611322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab416c85d48'
down_revision = 'f961d3adb6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('florafauna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('florafauna_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('florafauna_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('florafauna', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
